site_name: Learning Tutorials

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
- Home: 'index.md'
- Observational Astronomy: 
   - Julian Dates: 'ObservationalAstro/JD.md'
   - Is it observable: 'ObservationalAstro/Observable.md'
- MagneticFields:
   - Dipolar fields: 'MagneticFields/Dipole.md'
   - Field extrapolation: 'MagneticFields/FieldExtrapolation.md'
